/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "client_place.h"

airport_ret *
lat_longt_lookup_1_svc(char **argp, struct svc_req *rqstp)
{
	static airport_ret  result;

	/*
	 * insert server code here
	 */

	return &result;
}
