/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "place_airport.h"

bool_t
xdr_lat_long_input (XDR *xdrs, lat_long_input *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->lat))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->longitude))
		 return FALSE;
	return TRUE;
}
