/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACE_AIRPORT_H_RPCGEN
#define _PLACE_AIRPORT_H_RPCGEN

#include <rpc/rpc.h>
#include "client_place.h"

#ifdef __cplusplus
extern "C" {
#endif


struct lat_long_input {
	float lat;
	float longitude;
};
typedef struct lat_long_input lat_long_input;

#define DIRPROG2 0x31927172
#define DIR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define airport_lookup 1
extern  airport_ret * airport_lookup_1(lat_long_input *, CLIENT *);
extern  airport_ret * airport_lookup_1_svc(lat_long_input *, struct svc_req *);
extern int dirprog2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define airport_lookup 1
extern  airport_ret * airport_lookup_1();
extern  airport_ret * airport_lookup_1_svc();
extern int dirprog2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lat_long_input (XDR *, lat_long_input*);

#else /* K&R C */
extern bool_t xdr_lat_long_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACE_AIRPORT_H_RPCGEN */
