/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place_airport.h"
#include "client_place.h"

/*server*/
airport_ret *
lat_longt_lookup_1_svc(char **argp, struct svc_req *rqstp)
{
	static airport_ret  result;

	/*
	 * insert server code here
	 CALL DIRPROG2 HERE
	 */

	return &result;
}

/*client*/
void
dirprog2_1(char *host)
{
	CLIENT *clnt;
	airport_ret  *result_1;
	lat_long_input  airport_lookup_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DIRPROG2, DIR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = airport_lookup_1(&airport_lookup_1_arg, clnt);
	if (result_1 == (airport_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

/*
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dirprog2_1 (host);
exit (0);
}*/
